name=input("Enter your name:")
marks=input("Enter your Marks:")
ph_no=input("Enter your phone NUMBER:")
sentence="The name of student is {},\nHis marks is {}\n& Phone number is {}".format(name,marks,ph_no)
print(sentence)
print("\nSuccessfully executed")
